-- ==============================================================================
-- VIBE-FASHION 쇼핑몰 데이터베이스 스키마 (Supabase / PostgreSQL)
-- ==============================================================================

-- 1. 확장 기능 활성화
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. 공통 함수 정의 (updated_at 자동 갱신 및 관리자 확인)
-- ==============================================================================

-- 2-1. updated_at 자동 업데이트 트리거 함수
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2-2. 관리자 권한 확인 함수 (RLS 정책용)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 
        FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ==============================================================================
-- 3. 테이블 생성
-- ==============================================================================

-- 3-1. 회원 프로필 테이블 (auth.users와 1:1 연동)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    phone VARCHAR(30),
    avatar_url TEXT,
    role VARCHAR(20) DEFAULT 'customer' NOT NULL CHECK (role IN ('customer', 'admin')),
    grade VARCHAR(20) DEFAULT 'BRONZE' NOT NULL CHECK (grade IN ('BRONZE', 'SILVER', 'GOLD', 'VIP')),
    provider VARCHAR(50) DEFAULT 'email' NOT NULL, -- email, kakao, naver 등
    provider_id VARCHAR(100),                     -- 카카오 고유 회원 ID
    total_spent NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    order_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-2. 카테고리 테이블 (계층 구조 지원)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    sort_order INTEGER DEFAULT 0 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-3. 상품 테이블
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(280) NOT NULL UNIQUE,
    summary TEXT,
    description TEXT,
    original_price NUMERIC(12, 2) NOT NULL CHECK (original_price >= 0),
    sale_price NUMERIC(12, 2) CHECK (sale_price >= 0 AND sale_price <= original_price),
    stock_quantity INTEGER DEFAULT 0 NOT NULL CHECK (stock_quantity >= 0),
    status VARCHAR(20) DEFAULT 'active' NOT NULL CHECK (status IN ('draft', 'active', 'sold_out', 'hidden')),
    is_featured BOOLEAN DEFAULT false NOT NULL,
    view_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-4. 상품 옵션 테이블 (컬러, 사이즈 등)
CREATE TABLE IF NOT EXISTS public.product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    option_name VARCHAR(50) NOT NULL,    -- 예: '컬러', '사이즈'
    option_value VARCHAR(100) NOT NULL,  -- 예: '블랙', 'L'
    additional_price NUMERIC(12, 2) DEFAULT 0 NOT NULL,
    stock_quantity INTEGER DEFAULT 0 NOT NULL CHECK (stock_quantity >= 0),
    is_available BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-5. 상품 이미지 테이블
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER DEFAULT 0 NOT NULL,
    is_thumbnail BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-6. 장바구니 테이블
CREATE TABLE IF NOT EXISTS public.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    quantity INTEGER DEFAULT 1 NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uq_cart_user_product_option UNIQUE NULLS NOT DISTINCT (user_id, product_id, option_id)
);

-- 3-7. 주문 테이블
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    order_number VARCHAR(60) NOT NULL UNIQUE,
    status VARCHAR(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'paid', 'preparing', 'shipped', 'delivered', 'cancelled')),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    discount_amount NUMERIC(12, 2) DEFAULT 0 NOT NULL CHECK (discount_amount >= 0),
    shipping_fee NUMERIC(12, 2) DEFAULT 0 NOT NULL CHECK (shipping_fee >= 0),
    final_amount NUMERIC(12, 2) NOT NULL CHECK (final_amount >= 0),
    recipient_name VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(50) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    shipping_address TEXT NOT NULL,
    shipping_detail_address TEXT,
    shipping_memo TEXT,
    payment_method VARCHAR(50), -- card, transfer, kakaopay, naverpay 등
    payment_status VARCHAR(20) DEFAULT 'pending' NOT NULL CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
    paid_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-8. 주문 항목 테이블
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    option_id BIGINT REFERENCES public.product_options(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL, -- 주문 시점의 상품명 스냅샷
    option_description VARCHAR(255),    -- 주문 시점의 옵션명 스냅샷
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    total_price NUMERIC(12, 2) NOT NULL CHECK (total_price >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-9. 환불/반품 테이블
CREATE TABLE IF NOT EXISTS public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    refund_number VARCHAR(60) NOT NULL UNIQUE,
    refund_amount NUMERIC(12, 2) NOT NULL CHECK (refund_amount >= 0),
    reason TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'requested' NOT NULL CHECK (status IN ('requested', 'approved', 'rejected', 'completed')),
    admin_memo TEXT,
    requested_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-10. 알림 테이블
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    link TEXT,
    type VARCHAR(30) DEFAULT 'system' NOT NULL CHECK (type IN ('order', 'delivery', 'promotion', 'system')),
    is_read BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3-11. 리뷰 테이블
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    order_item_id BIGINT REFERENCES public.order_items(id) ON DELETE SET NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL,
    review_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ==============================================================================
-- 4. 인덱스 (조회 성능 최적화)
-- ==============================================================================

-- profiles
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_grade ON public.profiles(grade);

-- categories
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_sort ON public.categories(sort_order);

-- products
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products(created_at DESC);

-- product_options
CREATE INDEX IF NOT EXISTS idx_product_options_product_id ON public.product_options(product_id);

-- product_images
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images(product_id);

-- carts
CREATE INDEX IF NOT EXISTS idx_carts_user_id ON public.carts(user_id);

-- orders
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

-- order_items
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON public.order_items(product_id);

-- refunds
CREATE INDEX IF NOT EXISTS idx_refunds_order_id ON public.refunds(order_id);
CREATE INDEX IF NOT EXISTS idx_refunds_user_id ON public.refunds(user_id);
CREATE INDEX IF NOT EXISTS idx_refunds_status ON public.refunds(status);

-- notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_id_is_read ON public.notifications(user_id, is_read);

-- reviews
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);


-- ==============================================================================
-- 5. updated_at 트리거 연결
-- ==============================================================================

CREATE OR REPLACE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER trg_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER trg_carts_updated_at
BEFORE UPDATE ON public.carts
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER trg_refunds_updated_at
BEFORE UPDATE ON public.refunds
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON public.reviews
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();


-- ==============================================================================
-- 6. 소셜 로그인/회원가입 자동 프로필 생성 트리거 (handle_new_user)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_full_name TEXT;
    v_avatar_url TEXT;
BEGIN
    -- 소셜 로그인 제공자별 메타데이터(카카오, 구글, 네이버 등) 추출
    v_full_name := COALESCE(
        NEW.raw_user_meta_data->>'full_name',
        NEW.raw_user_meta_data->>'name',
        NEW.raw_user_meta_data->>'user_name',
        split_part(NEW.email, '@', 1)
    );

    v_avatar_url := COALESCE(
        NEW.raw_user_meta_data->>'avatar_url',
        NEW.raw_user_meta_data->>'picture',
        NEW.raw_user_meta_data->>'profile_image'
    );

    INSERT INTO public.profiles (
        id,
        email,
        full_name,
        avatar_url,
        role,
        grade,
        total_spent,
        order_count
    ) VALUES (
        NEW.id,
        NEW.email,
        v_full_name,
        v_avatar_url,
        'customer',
        'BRONZE',
        0,
        0
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        full_name = COALESCE(public.profiles.full_name, EXCLUDED.full_name),
        avatar_url = COALESCE(public.profiles.avatar_url, EXCLUDED.avatar_url);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- auth.users 테이블에 회원가입 시 트리거 작동
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ==============================================================================
-- 7. 고객 등급 및 누적 구매금액/주문횟수 자동 갱신 함수 (update_customer_grade)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.update_customer_grade()
RETURNS TRIGGER AS $$
DECLARE
    v_target_user_id UUID;
    v_total_spent NUMERIC(12, 2) := 0;
    v_order_count INTEGER := 0;
    v_new_grade VARCHAR(20) := 'BRONZE';
BEGIN
    -- INSERT/UPDATE 시 대상 사용자 ID 지정
    IF (TG_OP = 'DELETE') THEN
        v_target_user_id := OLD.user_id;
    ELSE
        v_target_user_id := NEW.user_id;
    END IF;

    -- 실 결제완료/배송 단계의 주문 건에 대한 실 결제금액 및 주문 횟수 집계
    -- (paid, preparing, shipped, delivered 상태 기준)
    SELECT 
        COALESCE(SUM(final_amount), 0),
        COUNT(*)
    INTO 
        v_total_spent,
        v_order_count
    FROM public.orders
    WHERE user_id = v_target_user_id
      AND status IN ('paid', 'preparing', 'shipped', 'delivered')
      AND payment_status = 'completed';

    -- 완료된 환불 금액이 있다면 총 결제금액에서 차감
    SELECT 
        GREATEST(v_total_spent - COALESCE(SUM(r.refund_amount), 0), 0)
    INTO
        v_total_spent
    FROM public.refunds r
    WHERE r.user_id = v_target_user_id
      AND r.status = 'completed';

    -- 등급 산정 기준 (쇼핑몰 정책에 맞게 금액/횟수 커스텀 가능)
    -- VIP    : 총 결제 1,000,000원 이상 또는 주문 10회 이상
    -- GOLD   : 총 결제 500,000원 이상 또는 주문 5회 이상
    -- SILVER : 총 결제 200,000원 이상 또는 주문 2회 이상
    -- BRONZE : 기본 등급
    IF (v_total_spent >= 1000000 OR v_order_count >= 10) THEN
        v_new_grade := 'VIP';
    ELSIF (v_total_spent >= 500000 OR v_order_count >= 5) THEN
        v_new_grade := 'GOLD';
    ELSIF (v_total_spent >= 200000 OR v_order_count >= 2) THEN
        v_new_grade := 'SILVER';
    ELSE
        v_new_grade := 'BRONZE';
    END IF;

    -- 프로필 테이블 갱신
    UPDATE public.profiles
    SET 
        total_spent = v_total_spent,
        order_count = v_order_count,
        grade = v_new_grade,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_target_user_id;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 주문 변경 시 고객 등급 갱신 트리거
DROP TRIGGER IF EXISTS trg_orders_update_grade ON public.orders;
CREATE TRIGGER trg_orders_update_grade
AFTER INSERT OR UPDATE OF status, payment_status, final_amount OR DELETE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.update_customer_grade();

-- 환불 상태 변경 시 고객 등급 갱신 트리거
DROP TRIGGER IF EXISTS trg_refunds_update_grade ON public.refunds;
CREATE TRIGGER trg_refunds_update_grade
AFTER INSERT OR UPDATE OF status, refund_amount OR DELETE ON public.refunds
FOR EACH ROW EXECUTE FUNCTION public.update_customer_grade();


-- ==============================================================================
-- 8. Row Level Security (RLS) 활성화 및 정책(Policies) 설정
-- ==============================================================================

-- 8-1. RLS 활성화
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 8-2. profiles 정책
-- 누구나 프로필 조회 가능 (리뷰 작성자 등 표시)
CREATE POLICY "profiles_select_all" 
ON public.profiles FOR SELECT 
USING (true);

-- 본인 프로필만 수정 가능
CREATE POLICY "profiles_update_own" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id) 
WITH CHECK (auth.uid() = id);

-- 8-3. categories 정책
-- 누구나 카테고리 조회 가능
CREATE POLICY "categories_select_public" 
ON public.categories FOR SELECT 
USING (is_active = true OR public.is_admin());

-- 관리자만 카테고리 추가/수정/삭제 가능
CREATE POLICY "categories_admin_all" 
ON public.categories FOR ALL 
USING (public.is_admin()) 
WITH CHECK (public.is_admin());

-- 8-4. products 정책
-- 활성 상품은 누구나 조회 가능 (관리자는 전체 조회 가능)
CREATE POLICY "products_select_public" 
ON public.products FOR SELECT 
USING (status = 'active' OR public.is_admin());

-- 관리자만 상품 등록/수정/삭제 가능
CREATE POLICY "products_admin_all" 
ON public.products FOR ALL 
USING (public.is_admin()) 
WITH CHECK (public.is_admin());

-- 8-5. product_options 정책
-- 누구나 조회 가능
CREATE POLICY "product_options_select_public" 
ON public.product_options FOR SELECT 
USING (true);

-- 관리자만 옵션 등록/수정/삭제 가능
CREATE POLICY "product_options_admin_all" 
ON public.product_options FOR ALL 
USING (public.is_admin()) 
WITH CHECK (public.is_admin());

-- 8-6. product_images 정책
-- 누구나 이미지 조회 가능
CREATE POLICY "product_images_select_public" 
ON public.product_images FOR SELECT 
USING (true);

-- 관리자만 이미지 등록/수정/삭제 가능
CREATE POLICY "product_images_admin_all" 
ON public.product_images FOR ALL 
USING (public.is_admin()) 
WITH CHECK (public.is_admin());

-- 8-7. carts 정책
-- 본인 장바구니만 조회, 추가, 수정, 삭제 가능
CREATE POLICY "carts_select_own" 
ON public.carts FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "carts_insert_own" 
ON public.carts FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "carts_update_own" 
ON public.carts FOR UPDATE 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "carts_delete_own" 
ON public.carts FOR DELETE 
USING (auth.uid() = user_id);

-- 8-8. orders 정책
-- 본인 주문 조회 또는 관리자 전체 조회
CREATE POLICY "orders_select_own_or_admin" 
ON public.orders FOR SELECT 
USING (auth.uid() = user_id OR public.is_admin());

-- 로그인한 사용자는 본인 주문 생성 가능
CREATE POLICY "orders_insert_own" 
ON public.orders FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 주문 상태 수정은 관리자만 또는 본인의 주문 취소(pending 상태)만 허용
CREATE POLICY "orders_update_admin_or_own_cancel" 
ON public.orders FOR UPDATE 
USING (
    public.is_admin() OR 
    (auth.uid() = user_id AND status = 'pending')
);

-- 8-9. order_items 정책
-- 주문 소유자 또는 관리자만 조회 가능
CREATE POLICY "order_items_select_own_or_admin" 
ON public.order_items FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.orders o
        WHERE o.id = order_items.order_id 
          AND (o.user_id = auth.uid() OR public.is_admin())
    )
);

-- 로그인한 사용자는 본인 주문의 항목 생성 가능
CREATE POLICY "order_items_insert_own" 
ON public.order_items FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.orders o
        WHERE o.id = order_items.order_id 
          AND o.user_id = auth.uid()
    )
);

-- 8-10. refunds 정책
-- 본인 환불 내역 조회 또는 관리자 전체 조회
CREATE POLICY "refunds_select_own_or_admin" 
ON public.refunds FOR SELECT 
USING (auth.uid() = user_id OR public.is_admin());

-- 본인 환불 요청 생성
CREATE POLICY "refunds_insert_own" 
ON public.refunds FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 관리자만 환불 처리/상태 변경 가능
CREATE POLICY "refunds_update_admin" 
ON public.refunds FOR UPDATE 
USING (public.is_admin()) 
WITH CHECK (public.is_admin());

-- 8-11. notifications 정책
-- 본인 알림만 조회 및 읽음 처리 가능
CREATE POLICY "notifications_select_own" 
ON public.notifications FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "notifications_update_own" 
ON public.notifications FOR UPDATE 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

-- 8-12. reviews 정책
-- 누구나 리뷰 조회 가능
CREATE POLICY "reviews_select_public" 
ON public.reviews FOR SELECT 
USING (true);

-- 본인만 리뷰 작성 가능
CREATE POLICY "reviews_insert_own" 
ON public.reviews FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 본인 또는 관리자만 리뷰 수정 및 삭제 가능
CREATE POLICY "reviews_update_own" 
ON public.reviews FOR UPDATE 
USING (auth.uid() = user_id OR public.is_admin()) 
WITH CHECK (auth.uid() = user_id OR public.is_admin());

CREATE POLICY "reviews_delete_own" 
ON public.reviews FOR DELETE 
USING (auth.uid() = user_id OR public.is_admin());
